---
- name: Installs a Central Logstash Server
  gather_facts: True
  hosts: all

  roles:
  - role: /home/vagrant/on-prem-lab/provisioning/roles/geerlingguy.java
    become: yes
  - role: /home/vagrant/on-prem-lab/provisioning/roles/elk-logstash
    vars:
      elasticsearch_server: http://localhost:9200
    become: yes    