
- name: make sure postgresql server is running
  service: name=postgresql state=started

- name: create database
  become_user: postgres
  postgresql_db: name={{ db_name }}

- name: create database user
  become_user: postgres
  postgresql_user: db={{ db_name }} name={{ db_user }} password={{ db_password }} priv=ALL
