##
# Set up all the dependencies in a virtualenv required by the Django app
##
- name: Create a virtualenv directory
  file: 
    path: "{{ venv_dir }}" 
    state: directory

- name: Install dependencies
  pip:    
    requirements: "{{ app_dir }}/requirements.txt"
    virtualenv: "{{ venv_dir }}"
    virtualenv_python: python3.6

- name: Install Openvas python lib
  shell: ". {{ install_root }}/envs/bin/activate && python3 -m pip install git+https://github.com/archerysec/openvas_lib.git "
  become: yes