##
# Set up Gunicorn and configure systemd to execute gunicorn_start script
##
- name: Create a deploy directory
  file: path={{ deploy_dir }} state=directory
  become: yes

- name: Create the gunicorn_start script for running our app from systemd service
#  template: src=gunicorn_start dest={{ deploy_dir }}/gunicorn_start owner=root group=root
  template:
    src: gunicorn_start
    dest: "{{ deploy_dir }}/gunicorn_start"
    owner: root
    group: root
    mode: a+rx
  become: yes

- name: Make the gunicorn_start script executable
  raw: cd {{ deploy_dir }}; chmod +x gunicorn_start
  become: yes