---
- name: Installs an ElasticSearch Server
  gather_facts: True
  hosts: all

  roles:
  # - role: /home/vagrant/on-prem-lab/provisioning/roles/geerlingguy.java
  #   become: yes
  - role: /home/vagrant/on-prem-lab/provisioning/roles/elk-elasticsearch
    vars:
      elasticsearch_server: 0.0.0.0
      elasticsearch_server_port: 9200
    become: yes       