- name: check if logstash configuration exists
  stat:
    path: "/etc/logstash/logstash.yml"
  register: logstash_check_configuration_file

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: logstash_check_configuration_file.stat.exists == false

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
  become: yes
  when: logstash_check_configuration_file.stat.exists == false  

- name: Install pre-requisites
  package:
    name: apt-transport-https
    update_cache: yes
    state: present

- name: Install logstash
  package:
    name: logstash
    update_cache: yes
    state: present
  register: get_result
  until: get_result is success
  retries: 3
  delay: 2          

- name: Copy the logstash config file
  template:
    src: logstash.yml
    dest: "/etc/logstash/logstash.yml"

- name: Copy the springular.conf file
  template:
    src: springular.conf.j2
    dest: "/etc/logstash/conf.d/springular.conf"
    owner: root
    group: root
    mode: a+r
  become: yes
  notify: Restart Logstash

