---
- name: Converge
  hosts: all

  pre_tasks:
    - name: install jdk 8
      become: yes
      package:
        name: java-1.8.0-openjdk-headless
        state: present
      register: get_result
      until: get_result is success
      retries: 3
      delay: 2

    - name: install find
      become: yes
      package:
        name: findutils
        state: present
      register: get_result
      until: get_result is success
      retries: 3
      delay: 2

  roles:
    - role: ansible-role-maven
      maven_version: '3.6.3'
      maven_install_dir: /opt/maven

  post_tasks:
    - name: verify default maven facts
      assert:
        that:
          - ansible_local.maven.general.version is defined
          - ansible_local.maven.general.home is defined
