---
- name: Ensure Pip is installed.
  package:
    name: "{{ pip_package }}"
    state: present
  register: get_result
  until: get_result is success
  retries: 3
  delay: 2

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
#   virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
    umask: "0022"
  with_items: "{{ pip_install_packages }}"
