[book]
authors = ["Anand Tiwari"]
language = "en"
multilingual = false
src = "src"
title = "NOTSOSECURE TRAINING GUIDE"

[output.html]
theme = "src/theme"
additional-css = ["src/theme/asciinema-player.css"]
additional-js = ["src/theme/asciinema-player.js"]