---
- name: Install Nginx config
  gather_facts: True
  hosts: all

  tasks:
    - name: Write nginx conf file
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: a+rx
      become: yes

    - name: Write nginx default conf file
      template:
        src: default.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: a+rx
      become: yes

    - name: restart nginx
      service: name=nginx state=restarted enabled=yes
      become: yes

    #    - name: create book dir
    #      command: mkdir /usr/share/nginx/html/book
    #      become: yes
    - name: Make static folder www-data
      file:
        path: "/home/vagrant/book"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: a+rx
        recurse: yes
      become: yes